### ISSUE TITLE
installation error with Python 3.8.6

### ISSUE THREAD

**Issue by JJ** [madzak/python-json-logger#100]
This is the error I get with Python freshly installed

```
Collecting python-json-logger
  Using cached python-json-logger-2.0.1.tar.gz (9.1 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/jmerelo/.pyenv/versions/3.8.6/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-asz9o06f/python-json-logger/setup.py'"'"'; __file__='"'"'/tmp/pip-install-asz9o06f/python-json-logger/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-n3lydwdw
         cwd: /tmp/pip-install-asz9o06f/python-json-logger/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/jmerelo/.pyenv/versions/3.8.6/lib/python3.8/site-packages/setuptools/__init__.py", line 23, in <module>
        from setuptools.dist import Distribution
      File "/home/jmerelo/.pyenv/versions/3.8.6/lib/python3.8/site-packages/setuptools/dist.py", line 34, in <module>
        from setuptools import windows_support
      File "/home/jmerelo/.pyenv/versions/3.8.6/lib/python3.8/site-packages/setuptools/windows_support.py", line 2, in <module>
        import ctypes
      File "/home/jmerelo/.pyenv/versions/3.8.6/lib/python3.8/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ModuleNotFoundError: No module named '_ctypes'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

it's probably not specific for this module, but I could actually get other modules to install correctly.

**Comment by JJ** [comment]
This was fixed by installing `libffi-dev` prior to installation of Python 3.8.6 via pyenv. Closing.
