### ISSUE TITLE
Fails on Python 3.9.1

### ISSUE THREAD

**Issue by ryboe** [madzak/python-json-logger#111]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/logging/config.py", line 655, in configure_formatter
    result = self.configure_custom(config)
  File "/usr/local/lib/python3.9/logging/config.py", line 474, in configure_custom
    result = c(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/pythonjsonlogger/jsonlogger.py", line 115, in __init__
    logging.Formatter.__init__(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'format'
```

**Comment by ryboe** [comment]
My mistake! This error was caused by a typo in a format string being passed to the custom JSON logger. Sorry for the noise.
