### ISSUE TITLE
OrderedDict causing recursion

### ISSUE THREAD

**Issue by gabrielfalcao** [madzak/python-json-logger#28]
Hi @madzak, this library is great and we're using it in production.
But when using it with tornado I can sometimes reproduce this:

``` python-traceback
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 859, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/Users/gabrielfalcao/.virtualenvs/device_management/lib/python2.7/site-packages/pythonjsonlogger/jsonlogger.py", line 117, in format
    log_record = OrderedDict()
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/collections.py", line 52, in __init__
    self.__update(*args, **kwds)
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

I don't have time to dig into this, because the output generated is actually obfuscating my actual error, but I hope that this bug report makes sense to you.

Thank you

**Comment by madzak** [comment]
Sorry never got to this. I don't have a tornado based app setup and I'm dropping support for 2.7. If you see it again in the recent versions feel free to reopen
